import { db } from '../src/compat.js';
import { emailAssets, shell, sendResend } from '../lib/order-email.js';
export const access='member';
export const methods=['POST'];
const clean=v=>String(v??'').trim();
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const site=req=>`https://${req.headers.host||'aliveraatelier.in'}`;
function emailShell(title,body,base){return `<div style="margin:0;background:#f7f1eb;padding:34px 14px;font-family:Arial,sans-serif;color:#241f26"><div style="max-width:680px;margin:auto;background:#fff;border:1px solid #e7ddd4"><div style="text-align:center;padding:26px 20px 18px;border-bottom:1px solid #eee4dc"><img src="${base}/api/brand/logo" alt="Alivèra Atelier" width="86" height="86" style="border-radius:50%;display:block;margin:0 auto 10px"><div style="font-family:Georgia,serif;letter-spacing:6px;font-size:20px">ALIVÈRA</div><div style="font-size:10px;letter-spacing:5px;margin-top:5px;color:#7e6c7e">ATELIER</div></div><div style="padding:30px 28px">${body}</div><div style="padding:18px 28px;border-top:1px solid #eee4dc;text-align:center;color:#7c7179;font-size:11px;letter-spacing:1px">BEAUTIFUL, JUST THE WAY YOU ARE. ♥</div></div></div>`}
function itemCards(items,assets){return items.map((x,i)=>`<div style="display:flex;gap:16px;padding:15px 0;border-bottom:1px solid #eee4dc">${assets.cards.split('</div></div>')[i]||''}</div>`).join('')}
export default async function(req,res){
 const b=req.body||{};const items=Array.isArray(b.items)?b.items:[];
 if(!items.length)return res.status(400).json({error:'Your bag is empty.'});
 const name=clean(b.customer_name),mail=clean(b.email).toLowerCase(),phone=clean(b.phone),address=clean(b.address),city=clean(b.city),state=clean(b.state),pincode=clean(b.pincode);
 if(!name||!mail||!phone||!address||!city||!state||!pincode)return res.status(400).json({error:'Please complete all delivery details.'});
 const ids=[...new Set(items.map(x=>x.product_id).filter(Boolean))];if(!ids.length)return res.status(400).json({error:'Invalid bag.'});
 const {rows:products}=await db.query("SELECT id,name,price,stock,active FROM products WHERE id = ANY($1::uuid[])",[ids]);
 const byId=new Map(products.map(p=>[String(p.id),p]));let subtotal=0;const checked=[];
 for(const item of items){const p=byId.get(String(item.product_id));const qty=Math.max(1,Math.min(10,Number(item.quantity)||1));if(!p||!p.active)return res.status(400).json({error:'A product in your bag is unavailable.'});if(Number(p.stock)>0&&Number(p.stock)<qty)return res.status(400).json({error:`Only ${p.stock} available for ${p.name}.`});const size=clean(item.size);const line=Number(p.price)*qty;subtotal+=line;checked.push({p,qty,size,customFit:!!item.custom_fit,line});}
 const promoCode=clean(b.promo_code).toUpperCase();let discount=0,campaign=null;
 if(promoCode){const {rows:cs}=await db.query("SELECT * FROM campaigns WHERE code=$1 AND active=true AND (starts_at IS NULL OR starts_at <= now()) AND (ends_at IS NULL OR ends_at >= now()) AND (max_uses IS NULL OR used_count < max_uses) LIMIT 1",[promoCode]);campaign=cs[0];if(!campaign)return res.status(400).json({error:'That discount code is not active or has expired.'});if(subtotal<Number(campaign.min_subtotal||0))return res.status(400).json({error:`This code requires a minimum order of ₹${Number(campaign.min_subtotal).toFixed(0)}.`});if(campaign.max_uses_per_customer){const {rows:uc}=await db.query("SELECT COUNT(*)::int AS count FROM orders WHERE lower(email)=lower($1) AND upper(coalesce(promo_code,''))=$2",[mail,promoCode]);if(Number(uc[0].count)>=Number(campaign.max_uses_per_customer))return res.status(400).json({error:'This discount has reached its limit for this customer.'});}discount=campaign.discount_type==='fixed'?Math.min(subtotal,Number(campaign.discount_value)):Math.min(subtotal,subtotal*Number(campaign.discount_value)/100);}
 const shipping=49,total=Math.max(0,subtotal-discount+shipping),payment=clean(b.payment_method)||'cod';
 const user=req.member;const orderNumber='ALV-'+Date.now().toString(36).toUpperCase();
 const {rows:orderRows}=await db.query("INSERT INTO orders (order_number,user_id,customer_name,email,phone,address,city,state,pincode,notes,subtotal,shipping,total,payment_method,promo_code) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id,order_number,total,status,payment_status",[orderNumber,user?.id||null,name,mail,phone,address,city,state,pincode,clean(b.notes),subtotal,shipping,total,payment,promoCode]);
 const order=orderRows[0];
 if(campaign)await db.query("UPDATE campaigns SET used_count=used_count+1, updated_at=now() WHERE id=$1",[campaign.id]);
 for(const x of checked){await db.query("INSERT INTO order_items (order_id,product_id,product_name,size,quantity,unit_price,line_total,custom_fit) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",[order.id,x.p.id,x.p.name,x.size,x.qty,x.p.price,x.line,x.customFit]);if(Number(x.p.stock)>0)await db.query("UPDATE products SET stock=GREATEST(stock-$1,0), updated_at=now() WHERE id=$2",[x.qty,x.p.id]);}
 const assets=await emailAssets(checked.map(x=>({product_id:x.p.id,product_name:x.p.name,size:x.size,quantity:x.qty,line_total:x.line,custom_fit:x.customFit})),req),cards=assets.cards,discountRow=discount?`<div>Discount${promoCode?` (${esc(promoCode)})`:''}: <b style="color:#6d5870">−₹${discount.toFixed(0)}</b></div>`:'';
 const summary=`<div style="background:#fbf7f3;padding:18px;margin-top:22px;line-height:1.8"><div>Subtotal: ₹${subtotal.toFixed(0)}</div>${discountRow}<div>Shipping: ₹${shipping.toFixed(0)}</div><div style="font-size:17px;margin-top:5px"><b>Total: ₹${total.toFixed(0)}</b></div></div>`;
 const ownerBody=`<p style="font-size:11px;letter-spacing:2px;color:#846f8a">NEW ORDER · ACTION REQUIRED</p><h1 style="font:500 30px Georgia,serif;margin:5px 0 12px">${esc(order.order_number)}</h1><p><b>${esc(name)}</b><br>${esc(mail)} · ${esc(phone)}<br>${esc(address)}, ${esc(city)}, ${esc(state)} ${esc(pincode)}</p><div style="margin-top:20px">${cards}</div>${summary}<p style="font-size:12px;color:#6e656d;margin-top:18px">Payment method: <b>${payment==='online'?'Online payment':'Pay on delivery'}</b>. Please review and confirm this order from Studio.</p>`;
 const customerBody=`<p style="font-size:11px;letter-spacing:2px;color:#846f8a">ORDER RECEIVED</p><h1 style="font:500 30px Georgia,serif;margin:5px 0 12px">Thank you, ${esc(name)}.</h1><p>We have received your Alivèra Atelier order <b>${esc(order.order_number)}</b>. It is currently awaiting owner confirmation.</p><div style="margin-top:18px">${cards}</div>${summary}<div style="margin-top:22px;padding:16px;border:1px solid #e8ddd4"><b>Deliver to</b><br>${esc(address)}, ${esc(city)}, ${esc(state)} ${esc(pincode)}<br>${esc(phone)}</div><p style="font-size:12px;color:#6e656d;margin-top:18px">We will send you another elegant confirmation email as soon as your order is confirmed.</p>`;
 try{await sendResend('contact@aliveraatelier.in',`ACTION REQUIRED — New Alivèra Atelier order ${order.order_number}`,shell(ownerBody),assets.attachments);}catch(e){console.log('Owner email notification failed',e?.message)}
 try{await sendResend(mail,`Order received · ${order.order_number} · Alivèra Atelier`,shell(customerBody),assets.attachments);}catch(e){console.log('Customer email notification failed',e?.message)}
 res.json({ok:true,order:order.order_number,total,payment_method:payment});
}